### ISSUE TITLE
The getter 'activeWidgetIds' was called on null

### ISSUE THREAD

**Issue by Bestfastfire** [simformsolutions/flutter_showcaseview#15]
Im getting this error when I tried use it:

```
The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(411.4, 683.4), devicePixelRatio: 2.6, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false)):
The getter 'activeWidgetIds' was called on null.
Receiver: null
Tried calling: activeWidgetIds
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ShowCaseWidget.activeTargetWidget (package:showcaseview/showcase_widget.dart:14:10)
#2      _ShowcaseState.showOverlay (package:showcaseview/showcase.dart:143:43)
#3      _ShowcaseState.didChangeDependencies (package:showcaseview/showcase.dart:136:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
```

Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G8030, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.0)
[✓] Connected device (1 available)

**Comment by simformsolutions** [comment]
@Bestfastfire can you please check this issue #9 ? feel free to re-open if it occurs again.
