### ISSUE TITLE
Error when using Hot Reload

### ISSUE THREAD

**Issue by isomdurm** [simformsolutions/flutter_showcaseview#52]
Hello! I'd like to start off by saying this is my first Issue creation, and it is an honor to do it on something I am clearly finding much use of. That being said, this is a first, so bear with me as a get a hold of the nuances of Issue submission.

 I implemented the example code into my dart, and it all works well, but any time I use Hot Refresh, like changing code and saving, I get a red screen with a stack error that only further breaks down the more I change code. The only fix is restarting the application. 

test device: iOS 13.2 iPhone X 

////////////////////////////////////////////////
Continuous Loop Break-Down Error (Restart Application to Fix)

Root Screen

class RootScreen extends StatefulWidget {
  RootScreen();

  @override
  _RootScreenState createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> {
  GlobalKey _one = GlobalKey();
  GlobalKey _two = GlobalKey();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Showcase(
        key: _one,
        description: ' Press and hold to create a new appointment ',
        showcaseBackgroundColor: Colors.blueAccent,
        textColor: Colors.white,
        child: Container(
          child: GestureDetector(
            onLongPress: () {
              ShowCaseWidget.of(context).startShowCase([_one, _two,]);
            },
            child: DayView(
              ...
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}

NavScreen 

class NavScreen extends StatefulWidget {
  @override
  _NavScreenState createState() => _NavScreenState();
}

class _NavScreenState extends State<NavScreen> {

  final List<Widget> _children = [
    HomeScreen(),
    RootScreen(),
  ];

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: new Stack(children: <Widget>[
        new Container(
          child: new Image.asset('assets/image.png', fit: BoxFit.contain),
        ),
        Scaffold(
          drawer: NavDrawer(),
          appBar: appBar,
          endDrawer: Drawer(),
          body: ShowCaseWidget(
            builder: Builder(
              builder: (context) => _children[_currentIndex],
            ),
          ),
        ),
      ],
      )
    );
  }
}

//////////////////////////////////////////////////////

Error:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Listener:
'package:flutter/src/rendering/box.dart': Failed assertion: line 1705 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  GestureDetector file:///Users/home_screen.dart:710:18
When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1705:18)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1711:6)
#4      _DayViewState.createEventsDrawProperties (package:flutter_week_view/src/day_view.dart:257:76)
#5      _DayViewState.didUpdateWidget (package:flutter_week_view/src/day_view.dart:109:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4694:58)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 869 libraries in 247ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4977 pos 14: '_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Builder file:///Users/home_screen.dart:972:22
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4977:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4979:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1944:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4560:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Brightness.light

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#0dc3d](dirty, state: _OverlayEntryWidgetState#a7163):
'package:flutter/src/rendering/object.dart': Failed assertion: line 2330 pos 12: 'attached': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/lib/main.dart:51:12
When the exception was thrown, this was the stack: 
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2330:12)
#3      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2271:39)
#4      AnchoredOverlay.build.<anonymous closure>.<anonymous closure> (package:showcaseview/layout_overlays.dart:68:34)
#5      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:177:34)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by isomdurm** [comment]
Can Confirm that this is directly an issue with another package I am using, flutter_week_view, my apologies
